# CRIE UM PROGRAMA QUE TENHA UMA FUNÇÃO CHAMADA VOTO() QUE VAI RECEBER COMO
# PARAMENTRO O ANO DE NASCIMENTO DE UMA PESSOA, RETORNANDO UM VALOR LITERAL INDICANDO
# SE UMA PESSOA, RETORNANDO UMA VALOR LITERAL
# INDICANDO SE UMA PESSOA TEM VOTO NEGADO, OPCIONAL E OBRIGATÓRIO NAS ELEIÇOES.